/**
 * 
 * YOU CAN GET THE CODE THAT YOU WANT ON ES-FOLDERS
 * COPY THE CODE AND PUT HERE ON INDEX.JS
 * GO TO YOUR BROWSER AND SEE THE RESULT ON CONSOLE.
 * 
 * 
 * YOU CAN CONTRUBUTE IF YOU WANT, TO IMPROVE THE WAY
 * THAT THIS WORKS, BECAUSE NOW IT'S ONLY BY COPY AND PASTE :P
 * 
 */